### ISSUE TITLE
object files

### ISSUE THREAD

**Issue by K1773R** [AwlsomeAlex/AwlsomeOS#2]
Hey there

Just saw you have object files (*.o) which shouldnt be commited to git.
You can exclude certain patterns with a .gitignore file.

**Comment by AwlsomeAlex** [comment]
@K1773R Thanks, I was planning on adding a .gitiqnore, but wasn't sure if they were needed in debugging my latest issue with Interrupts. I'll probably be rewriting AwlsomeOS based on the last release so I'll be sure to add it in then.
